name = "DitherPunk"
uuid = "b8f752a5-abd5-43b6-a55b-e75efda20de0"
authors = ["Adrian Hill"]
version = "4.0.0-DEV"

[deps]
ColorQuantization = "652893fb-f6a0-4a00-a44a-7fb8fac69e01"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
IndirectArrays = "9b13fd28-a010-5f03-acff-a1bbcff69959"
UnicodeGraphics = "ebadf6b4-db70-5817-83da-4a19ad584e34"

[compat]
ColorQuantization = "0.1"
ColorSchemes = "3"
ColorTypes = "0.11, 0.12"
Colors = "0.12, 0.13"
ImageCore = "0.10"
IndirectArrays = "1"
UnicodeGraphics = "0.2"
julia = "1.6"
